{MOVE, TURN(ANGLE, 1 * SCALE, -1.5 * SCALE)},
    {DRAW, TURN(ANGLE, -2 * SCALE, 0 * SCALE)},
    {DRAW, TURN(ANGLE, 0 * SCALE, 1.5 * SCALE)},
    {DRAW, TURN(ANGLE, 0 * SCALE, 1.5 * SCALE)},
    {DRAW, TURN(ANGLE, 2 * SCALE, 0 * SCALE)},
    {DRAW, TURN(ANGLE, -1 * SCALE, -1 * SCALE)},
    {DRAW, TURN(ANGLE, 0 * SCALE, -1 * SCALE)},
    {DRAW, TURN(ANGLE, 1 * SCALE, -1 * SCALE)},
{
    STOP, TURN(ANGLE, -1 * SCALE, 1.5 * SCALE)
}
